/* A packrat parser generated by PackCC 1.2.2 */

#ifndef PCC_INCLUDED_LEE_PARSER_H
#define PCC_INCLUDED_LEE_PARSER_H

#define lee_parser lee_parser_context_t
#define lee_parser_new lee_parser_create

#include "lee.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct lee_parser_context_tag lee_parser_context_t;

lee_parser_context_t *lee_parser_create(void *auxil);
int lee_parser_parse(lee_parser_context_t *ctx, node**ret);
void lee_parser_destroy(lee_parser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_LEE_PARSER_H */
